fix: extract current port

diff --git a/.github/workflows/Deploy.yaml b/.github/workflows/Deploy.yaml
--- a/.github/workflows/Deploy.yaml
+++ b/.github/workflows/Deploy.yaml
@@ -31,17 +31,28 @@ jobs:
             if [ ! -f "${NGINX_CONF}" ]; then
               echo "Error: Nginx configuration file not found at ${NGINX_CONF}."
               exit 1
+            
+            else
+              echo "Nginx configuration file found at ${NGINX_CONF}."
             fi
 
-            # Nginx 설정에서 현재 포트 확인
-            CURRENT_PORT=$(grep -oP '(?<=proxy_pass http://localhost:)\d+' "${NGINX_CONF}")
-            if [ "\${CURRENT_PORT}" -eq 3030 ]; then
+            # 현재 포트 확인 (upstream backend에서 추출)
+            CURRENT_PORT=$(grep -A 1 "upstream backend" "$NGINX_CONF" | grep -Po '\d+')
+
+            # 포트가 제대로 추출되었는지 확인
+            if [ -z "$CURRENT_PORT" ]; then
+              echo "Error: Could not find the current port in $NGINX_CONF."
+              exit 1
+            fi
+
+            # 다음 포트 계산
+            if [ "$CURRENT_PORT" -eq 3030 ]; then
               NEXT_PORT=3031
             else
               NEXT_PORT=3030
             fi
 
-            echo "Current port: \${CURRENT_PORT}, Next port: \${NEXT_PORT}"
+            echo "Current port: $CURRENT_PORT, Next port: $NEXT_PORT"
 
             # 새로운 컨테이너 실행
             docker pull ghcr.io/${{ github.repository_owner }}/my-app:latest
